// What Sadie says while the child paints. Strings are one line; arrays are picked
// from at random. Short and simple: nothing may depend on reading them.
export const PAINTING_LINES = {
  easel: ['Pick a paint pot, then paint on the paper.', "Paper's ready. Show me what you've got.", 'Brush, sponge, cloth. Everything is on the shelf.'],
  colors: {
    red: 'Red! Like a tomato.', orange: 'Orange. My favorite food color.', yellow: 'Yellow, like the sun.',
    green: 'Green. Like Fern!', blue: "Blue like the sky. Or a fish's dream.", purple: 'Purple. Very fancy.',
    pink: 'Pink, like my nose. Excellent choice.', brown: 'Brown, like a cozy tree.', black: 'Black. Good for outlines.', white: 'White! Good for clouds.',
  },
  tools: {
    brushS: 'The little brush. For tiny details.', brushB: 'The big brush. For big ideas.',
    sponge: 'The sponge goes dab, dab, dab.', cloth: 'The cloth wipes paint away.',
  },
  stamps: { sadie: "That's me. I'm very easy to draw.", chooter: 'Chooter! He would say hi, but he is a dog.' },
  stampDone: ['Stamp!', 'Thump. Right where you wanted it.'],
  clearHint: 'Hold the bucket down to wipe the whole paper clean.',
  cleared: ['All clean. A fresh start!', 'Whoosh. Clean paper.'],
  alreadyClean: 'The paper is already clean.',
  undone: ['Undone.', 'Back it goes.', 'Poof. Gone.'],
  nothingToUndo: 'Nothing to undo.',
  zoomed: 'Pinch to zoom. Tap twice to see the whole paper.',
  tabs: 'Pull a tab out for more paper. Push it in for less.',
  wall: "That's the wall. There is no more paper.",
  tabsDone: 'Your painting stays right where it is.',
  first: 'Oh! You started. Good.',
  praise: ['Hmm. Not bad at all.', 'Ooh. I see what you are doing.', 'Keep going. I am watching.', 'That part is my favorite.', "Hmph. That's actually very good.", 'Bold! I like bold.'],
  many: 'So many colors. Very brave.',
  wipe: 'Wiping is fine. Real artists do it all the time.',
  empty: 'The paper is empty! Paint something first.',
  hung: ["Hmph. It's wonderful. Don't tell anyone I said so.", 'Up it goes! The studio looks better already.', "A masterpiece. I'll allow it."],
  saving: 'Saving it for you. Hold still. I mean, the painting.',
  toBook: ['Into the book it goes. Safe and sound.', 'The book will keep it. It is a very good book.'],
  booked: ['The line is full, so this one goes in the book.', 'Into the book. Nothing gets thrown away here.'],
  lineFull: 'The clothesline is full. Put one in the book first.',
  deleted: ['Poof. Gone for good.', 'All gone. I will pretend I never saw it.'],
  backingUp: 'Packing every painting into one file. Keep it safe.',
  restoring: 'Let me see what is in that file.',
  restoredNone: 'I already have all of those. Nothing new.',
  restoredBig: 'That file is far too big for me. I cannot carry it.',
  restoredBad: 'That file is not mine. I cannot read it.',
  deleteHint: 'Hold the trash can down to throw it away.',
  bookOpen: ['The book. Paintings sleep here when the line is full.', 'All the paintings that ran out of string.'],
  reopen: ['Back to work on this one?', 'Touch-ups? I allow it.', 'Ooh, a second go. Brave.'],
  bookEmpty: 'Nothing in the book yet.',
  bookBye: 'The book stays here. Paintings are safe in it.',
  fromBook: ['Back on the line! Fresh air.', 'Up it goes again.'],
  bye: 'Your painting will wait on the easel.',
  art: ['I remember this one. Still good.', 'Hanging art is the best part.', "Very nice. I'd sniff it."],
};
